---
- hosts: dbnew
  sudo: yes
  vars:
    - galera_cluster_name: cluster_one
    - galera_cluster_members: [ server1, server2, server3 ]
  roles:
    - galera
  environment:
    http_proxy: http://

