---
# Configure system users access to MariaDB

#Start SQL after Install
- name: Ensure mariadb is running and configured to start at boot
  service: name=mysql state=started enabled=yes

#Change root Password
- name: Set MariaDB root password for local login
  mysql_user: login_user=root
              login_password=''
              name=root 
              password={{ galera_root_password }} 
              host=localhost 
  ignore_errors: true

#Add root default file for mysql access  
- name: Configure MariaDB root defaults-file
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0640 force=yes

