---
#
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - MySQL-python.x86_64
    - MariaDB-client.x86_64
    - MariaDB-Galera-server.x86_64
    - galera.x86_64
