---
#
- name: Install required packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 11400
  with_items:
    - python-mysqldb
    - MariaDB-client
    - MariaDB-Galera-server
    - galera
