---
#
- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-mysqldb
    - MariaDB-client
    - MariaDB-Galera-server
    - galera
