---
# tasks file for galera
#

- include: repository.yml
  tags: repository

- include: packages.yml
  tags: packages

- include: access.yml
- include: secure.yml
- include: config.yml

- meta: flush_handlers
